name: Release Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-video
      - run: mkdocs gh-deploy --force
